language: node_js
node_js:
  - "9"
  - "node"
notifications:
  email: false
before_deploy: "yarn build"
deploy:
  provider: firebase
  token:
    secure: qSsuWmhjbRyD+gDPGoqkb4eAa3pG84MSe0Thyi922tDYwBMpthqbndp1bq88QP9UHbA4h+hTo0iBcfZkAwxC0yOg84YRLipvrofw30wMFul1PwKfzSAn4FX3gbGruTBd4fXelQ7y/dHfst+4HKG5JOsPf7DdPRsBjqhVHcDqvC5P2bsxFHI3lz0mMy9RUgh7JVl0ir+dZQBaozJygiMNRWue3Nw1uoS3twPonFqI0bmmT/7+bnIuIqAfAEoZWUm2lka+d/tg7PCg8maxVcv8FHoBruvb5Ajsp6iZfPYg+7Y/7FGBX7EAmv1neEBu5cfwuZadDFhsARSt6bBnZBsnd2wzV0uYgb8HLzHpApMe+hi1tONGquEWWxjvFZZV5pr8+gCrFqFzW1sHQ2OHSJ0yPOjHQHaC4lEwh7NXS/heOMw5Zxubqmjk/WZOWTRiVws2Gm36ehe0bf/5WFL9aEZaPqNLcBgEFTDF8OGPXO7zi07SA4hEPcn9t3/0CPrYWbFeI8OTxTcK+AYA2H3jdTOnAYqeKeism7qvJAM/vjjn31RSQ9ZR2WP+mfYI+QswowenOwZ+9WbRDuHz3XfbxE+TNAxnWArOohtdgt9tWgi6zDy/jzSW209hNE5jTOhku4levBdJL7UPThjo3fqPwvwDX6APFnK9Ogo3MjQ6immE2a8=
  on:
    node: "9"
